### ISSUE TITLE
2x2 grid not working 

### ISSUE THREAD

**Issue by ozcodex** [BrunoMine/craft_table#1]
Hey man, is sad to say, but the mod is not working properly.

I tried in a clean installation of minetest from snap, only with this mod enabled, and every time that i try to use it the objects return to my inventory and i cant craft anything.

```
$ minetest --version
Minetest 5.3.0 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/share/minetest"
STATIC_LOCALEDIR="/share/locale"
```

Later i will record a video about it so you can see what I mean.

**Comment by ozcodex** [comment]
here it is: [Youtube Video](https://youtu.be/MPwZ9kCbhoY)

tell me if you need more information or help with something

**Comment by ozcodex** [comment]
here: [Youtube Video part 2](https://youtu.be/PmOks6QskXw)

You can see how it works after put it on creative (put an object on the grid) and back to survival, and it works well... until I restart the game:

PD: if you don't put an object on the grid while you are on creative this solution didn't work

**Comment by BrunoMine** [comment]
I am checking the error. Thank you for report

**Comment by BrunoMine** [comment]
Okay, update you mod version now and test please.
Destroy the old world and try again

**Comment by ozcodex** [comment]
It seems like working fine, thank you so much!!!!
This is the things that I love from open source community.
